### PR TITLE
make `toString()` on `SplitEvent` public

### PR DESCRIPTION
**Pull request by ohwhen**
# iOS SDK

## What did you accomplish?

Tiny PR to make the `toString()` method public.

### CODE REVIEW

**Comment by ohwhen** [comment]
@javrudsky can we land this pls?

**Review by javrudsky — APPROVED** [review]
👍

**Comment by ohwhen** [comment]
@javrudsky thanks for the stamp, looks like it needs approval to run the required checks. I've also rebased my changes onto the development branch instead.

**Comment by ohwhen** [comment]
@javrudsky I can't merge this because the workflows cannot run without approval

**Comment by javrudsky** [comment]
Hi @ohwhen , thank you for your contribution. I'll merge the changes as soon the checks run.

**Comment by ohwhen** [comment]
Thanks @javrudsky looks like there are some flaky tests...let me know if I can help here, happy to chime in.

**Comment by javrudsky** [comment]
Hi @ohwhen! 
Yes, after updating GHA vm to Xcode 15, we've encountered some issues. I can offer two options:

1. You can merge (or rebase) the development branch into your branch.
2. I can create a new, small PR from our branch.

Please let me know which option you prefer.

**Comment by ohwhen** [comment]
> 1. You can merge (or rebase) the development branch into your branch.
> 2. I can create a new, small PR from our branch.
> 
> Please let me know which option you prefer.

@javrudsky no worries, just rebased `development` onto my branch, hopefully this should do the trick 🤞

**Comment by ohwhen** [comment]
@javrudsky not sure why these tests keep failing, I'm happy to rebase or fix my PR but kinda feels this small of a change can just be force-merged without harm? ☺️

**Comment by ohwhen** [comment]
@javrudsky anything I can do to help land this super tiny change? ☺️

**Comment by ohwhen** [comment]
@javrudsky just rebased latest development onto my branch so hopefully this should be ready to be merged now 🤞

**Comment by javrudsky** [comment]
Thank you for your contribution @ohwhen!!

**Pull request merged**
