### PR TITLE
fix Xcode 11 warnings, test warnings

### PR DESCRIPTION
**Pull request by dvshelley**
# iOS SDK
Xcode 11.2.1
## What did you accomplish?
fix warnings related to Xcode 11
fix warnings in unit tests
## How do we test the changes introduced in this PR?
use Xcode 11 and this project, compile -> no warnings
## Extra Notes

### CODE REVIEW

**Comment by dvshelley** [comment]
This PR fixes a number of warnings in the codebase.

**Comment by NicoZelaya** [comment]
Hi @dvshelley ! Thank you very much for your contribution. 

We'll take it from here and merge it against our development branch from where we'll release this fixes along with some other updates.

Best,
Nico.

**Comment by NicoZelaya** [comment]
Hi @dvshelley !

Hope you're having a wonderful week. We started from your updates and fixed the warnings in version 2.5.1, currently merged to master. Would you mind giving it a try? 

I'm closing the PR for now since we shouldn't need to merge it but let us know if you're still experiencing any issues and we'll address those too.

Best,
Nico.

**Comment by dvshelley** [comment]
> Hi @dvshelley !
> 
> Hope you're having a wonderful week. We started from your updates and fixed the warnings in version 2.5.1, currently merged to master. Would you mind giving it a try?
> 
> I'm closing the PR for now since we shouldn't need to merge it but let us know if you're still experiencing any issues and we'll address those too.
> 
> Best,
> Nico.

2.5.1 looks great! thanks!

**Pull request closed without merging**
